language: python

dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - TOXENV=py-django111-mysql
  - TOXENV=py-django111-postgres
  - TOXENV=py-django111-sqlite
  - TOXENV=py-django20-mysql
  - TOXENV=py-django20-postgres
  - TOXENV=py-django20-sqlite
  - TOXENV=py-django21-mysql
  - TOXENV=py-django21-postgres
  - TOXENV=py-django21-sqlite

matrix:
  exclude:
    - python: "2.7"
      env: TOXENV=py-django20-mysql
    - python: "2.7"
      env: TOXENV=py-django20-postgres
    - python: "2.7"
      env: TOXENV=py-django20-sqlite
    - python: "2.7"
      env: TOXENV=py-django21-mysql
    - python: "2.7"
      env: TOXENV=py-django21-postgres
    - python: "2.7"
      env: TOXENV=py-django21-sqlite
  fast_finish: true

services:
  - mysql
  - postgresql

before_install:
  - pip install tox
  - if [[ $TOXENV == *mysql ]]; then mysql -e 'CREATE DATABASE test_db;'; fi
  - if [[ $TOXENV == *postgres ]]; then psql -c 'CREATE DATABASE test_db;' -U postgres; fi

script: tox

cache:
  pip: true

stages:
  - test
  - deploy

jobs:
  include:
    - stage: deploy
      script: skip
      env:
      after_success:
        - codecov -e TOXENV
      deploy:
        provider: pypi
        distributions: sdist
        user: RegioHelden
        password:
          secure: "PkVBx/TNbXeGNbhUcfhqLAMIIASRMk/zfRv1P3U3hRRESHBZdnxvbRgu2KsUPgdFArxpg1YkF25fdcZU//PeiKbwCa7z8taUFXZW6MEdZtzixITLyTMIrQl0iWFe2tqHxDIe6kH9LeNLbBtUsXUnwamfb0XISiN3mrD8JHqr55qCQ8jcNM5i2Kp7zfH5jdoVBmZYb8rWJDAozwOU+ZxUSStWMrtbz7iI9FaLDHiDVRjQ+L45ASUYPe32TAyKCTAMvNmR9DeMuXEFnKmdxBtbem9EPh2+QYGnAb7TsRIO4onHgu9mG9mY1UD22Rgvu/RURV/w8fazZPKmSW/sj17P3B9lcSYSEPHP+XdqRmL2e5Eakfxr7IO8HX0b1DxA8f9RKrjFJtIQ2Xgap/gaJv83W6HhdsQ4Cv8wliNDHp4spoloeKHmQa7+7X66w7A6zKTseUafBz0qPc9qPq6kNOWoVgCinll+Fzc8ETM/npln53va3nPZ7sKWHy6s1BYhjh3jTviFtpW66CR9Jf1pePFujSB2xXhx7KoO2EiREFuavz11B7vy/sfvzZTYx1eV9tmunhDL06hDh/Bw7I8UfhYQfnGtwnN6jYXuw9X3WISaxFXrQSY1HYKlkXHUCMFpAbZDN+XAIWhnxEfwuoH2sQwG3uLzX/flDuzslyOnGcTrFOw="
        on:
          tags: true
